### ISSUE TITLE
Mobile: Fix status message placement

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em-proto#102]
The status message (Connecting, Offline, etc) should be `position: fixed` in the upper right hand corner regardless of desktop or mobile. It was not properly repositioned when moved to the footer on mobile.

Use the same _effective_ (i.e. visible) margin and padding as the current desktop positioning. 

See `/components/Footer.js` and `App.css`

**Comment by thackley** [comment]
In `browser.js` `isMobile =  true` to test for mobile.
