### ISSUE TITLE
Cmd + Shift + H → Home

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em-proto#76]
- Add "Command (or Control on Windows) + Shift + H" keyboard shortcut to navigate to the home screen.
- See `shortcuts.js` for shortcut definitions
- See `<HomeLink>` for example of navigation to home screen

**Comment by miladkdz** [comment]
I’ll take this one too 🙂

**Comment by raineorshine** [comment]
@miladkdz Actually this was already done! Closing.
